remove bench/huandu-skiplist/huandu-skiplist_test.go
redo        bench/huandu-skiplist.test
huandu-skiplist/huandu-skiplist_test.go:22:24: cannot use huandySpec{} (value of type huandySpec) as type skiplist.Comparable in argument to skiplist.New:
	huandySpec does not implement skiplist.Comparable (missing CalcScore method)